import os, sys
import json

script_path = sys.argv[0]
tests_path = sys.argv[1]
repository_path = sys.argv[2]

assert os.path.exists(f"{repository_path}/v1/00.json"), "sm83 directory is not checked out"

SUPPORTED_OPCODES = ([
    (0x00,"nop"), # NOP
    (0x02,"ld"), # LD [BC], A
    (0x0A,"ld"), # LD A, [BC]
    (0x12,"ld"), # LD [DE], A
    (0x1A,"ld"), # LD A, [DE]
    (0x40,"ld"), # LD B, B
    (0x47,"ld"), # LD B, A
    (0x49,"ld"), # LD C, C
    (0x52,"ld"), # LD D, D
    (0x5B,"ld"), # LD E, E
    (0x64,"ld"), # LD H, H
    (0x6D,"ld"), # LD L, L
    (0x78,"ld"), # LD A, B
    (0x7F,"ld"), # LD A, A
])

for info in SUPPORTED_OPCODES:
    opcode = info[0]
    insn = info[1]
    input_filename = os.path.join(f"{repository_path}/v1", (f"{opcode:02X}.json").lower())
    output_filename = f"{tests_path}/sm83_{opcode:02X}.cpp"
    with open(input_filename, "r") as input_fn, open(output_filename, "w", encoding="utf-8") as output_fn:
        input_json = json.load(input_fn)

        output_fn.write(f"// File autogenerated by {script_path}\n")
        output_fn.write(f"#include <test/include/acutest.h>\n\n")
        output_fn.write(f"#include <cpu/include/instruction_{insn}.hpp>\n")
        output_fn.write(f"#include <cpu/include/registers.hpp>\n")
        output_fn.write(f"#include <memory/include/memory.hpp>\n\n")

        output_fn.write(f"using namespace pgb::common;\n")
        output_fn.write(f"using namespace pgb::memory;\n")
        output_fn.write(f"using namespace pgb::cpu;\n\n")

        output_fn.write(f"static auto registers = RegisterFile();\n")
        output_fn.write(f"static auto mmap      = MemoryMap(registers, MaxRomBankCount, MaxVramBankCount, MaxEramBankCount, MaxWramBankCount);\n\n")

        output_fn.write(f"""
#define WriteRegisterWord(register, value) do {{ auto result = mmap.WriteWord(register, value); TEST_ASSERT(result.IsSuccess()); }} while(0)
#define WriteRegisterByte(register, value) do {{ auto result = mmap.WriteByte(register, value); TEST_ASSERT(result.IsSuccess()); }} while(0)
#define WriteRegisterFlag(value) do {{ TEST_ASSERT(static_cast<const Byte>(mmap.WriteFlagByte(static_cast<const Byte&>(value))) == 0x00); }} while(0)
#define WriteMemory(address, value) do {{ auto result = mmap.WriteByte(address, value); TEST_ASSERT(result.IsSuccess()); }} while(0)

#define CheckRegisterWord(register, value) do {{ auto result = mmap.ReadWord(register); TEST_ASSERT(result.IsSuccess()); TEST_ASSERT(static_cast<const Word&>(result) == value); }} while(0)
#define CheckRegisterByte(register, value) do {{ auto result = mmap.ReadByte(register); TEST_ASSERT(result.IsSuccess()); TEST_ASSERT(static_cast<const Byte&>(result) == value); }} while(0)
#define CheckRegisterFlag(value) do {{ TEST_ASSERT(static_cast<const Byte>(mmap.ReadFlagByte()) == value); }} while(0)
#define CheckMemory(address, value) do {{ auto result = mmap.ReadByte(address); TEST_ASSERT(result.IsSuccess()); TEST_ASSERT(static_cast<const Byte&>(result) == value); }} while(0)

static_assert(instruction::InstructionRegistryNoPrefix::Callbacks[0x{opcode:02X}] != nullptr);
static_assert(instruction::InstructionRegistryNoPrefix::Ticks[0x{opcode:02X}] != 0);
        """)

        test_names = []
        test_content = []
        for test in input_json:
            test_name = test['name'].replace(' ', '_')
            test_names.append(test_name)
            test_content.append(f"""
void test_{test_name}()
{{
    mmap.Reset();
    TEST_ASSERT(mmap.Initialize(MaxRomBankCount, MaxVramBankCount, MaxEramBankCount, MaxWramBankCount).IsSuccess());

    // Initial state
""")
            # These tests assume '64K of flat ram (Address range from 0x0000 to 0xFFFF)
            # No point bank swapping, just assume raw data
            for val in test['initial']:
                if val in ("pc", "sp"):
                    address = test['initial'][val]
                    assert address <= 0xFFFF
                    test_content.append(f"    WriteRegisterWord(RegisterType::{val.upper()}, 0x{address:04X});")
                elif val in ("a", "b", "c", "d", "e", "h", "l", "ie"):
                    test_content.append(f"    WriteRegisterByte(RegisterType::{val.upper()}, 0x{test['initial'][val]:02X});")
                elif val == 'f':
                    test_content.append(f"    WriteRegisterFlag(0x{test['initial'][val]:02X});")
                elif val == 'ime':
                    v = test['initial'][val]
                    assert v in (0, 1)
                    if v == 0:
                        test_content.append(f"    mmap.DisableIME();")
                    else:
                        test_content.append(f"    mmap.EnableIME();")
                elif val == "ram":
                    for ram in test['initial'][val]:
                        test_content.append(f"    WriteMemory(0x{ram[0]:04X}, 0x{ram[1]:02X});")

            test_content.append(f"""
    // Execute single step
    {{
         auto resultByte = mmap.ReadByte(mmap.ReadPC());
         TEST_ASSERT(resultByte.IsSuccess());
         auto ticks = instruction::InstructionRegistryNoPrefix::Execute(static_cast<const Byte&>(resultByte), mmap);
         TEST_ASSERT(ticks == instruction::InstructionRegistryNoPrefix::Ticks[static_cast<const Byte&>(resultByte)]);
    }}

    // Final state
            """)

            for val in test['final']:
                if val in ("pc", "sp"):
                    address = test['initial'][val]
                    assert address <= 0xFFFF
                    test_content.append(f"    WriteRegisterWord(RegisterType::{val.upper()}, 0x{address:04X});")
                elif val in ("a", "b", "c", "d", "e", "h", "l", "ie"):
                    test_content.append(f"    CheckRegisterByte(RegisterType::{val.upper()}, 0x{test['final'][val]:02X});")
                elif val == 'f':
                    test_content.append(f"    CheckRegisterFlag(0x{test['final'][val]:02X});")
                elif val == 'ime':
                    v = test['final'][val]
                    assert v in (0, 1)
                    if v == 0:
                        test_content.append(f"    TEST_ASSERT(!mmap.IMEEnabled());")
                    else:
                        test_content.append(f"    TEST_ASSERT(mmap.IMEEnabled());")
                elif val == "ram":
                    for ram in test['final'][val]:
                        test_content.append(f"    CheckMemory(0x{ram[0]:04X}, 0x{ram[1]:02X});")

            test_content.append(f"}}")

        for name in test_names:
            output_fn.write(f"void test_{name}(void);\n")

        output_fn.write(f"TEST_LIST = {{\n")
        for name in test_names:
            output_fn.write(f"    {{ \"{name}\", test_{name} }},\n")
        output_fn.write(f"    {{NULL, NULL}}\n")
        output_fn.write(f"}};\n")

        for content in test_content:
            output_fn.write(content)
            output_fn.write("\n")
