import os, sys
import json

script_path = sys.argv[0]
file_path = os.path.join(os.path.dirname(script_path), "Opcodes.json")
test_path = sys.argv[1]

with open(file_path, 'r') as input_fn, open(test_path, 'w', encoding='utf-8') as output_fn:
    input_json = json.load(input_fn)

    output_fn.write(f"// File autogenerated by {script_path}\n")
    output_fn.write(f"#include <test/include/acutest.h>\n\n")
    output_fn.write(f"#include <cpu/include/cpu.hpp>\n")
    output_fn.write(f"""
TEST_LIST = {{
    {{NULL, NULL}}
}};

using namespace pgb::cpu::instruction;

""")
    unprefixed = input_json["unprefixed"]
    cbprefixed = input_json["cbprefixed"]

    for opcode in unprefixed:
        length = unprefixed[opcode]["bytes"]
        output_fn.write(f"static_assert(InstructionRegistryNoPrefix::Callbacks[0x{int(opcode, 16):02X}] == nullptr || InstructionRegistryNoPrefix::Lengths[0x{int(opcode, 16):02X}] == {length});\n")

    for opcode in cbprefixed:
        length = unprefixed[opcode]["bytes"]
        output_fn.write(f"static_assert(InstructionRegistryPrefixCB::Callbacks[0x{int(opcode, 16):02X}] == nullptr || InstructionRegistryPrefixCB::Lengths[0x{int(opcode, 16):02X}] == {length});\n")
