import os, sys
import json

script_path = sys.argv[0]
tests_path = sys.argv[1]
repository_path = sys.argv[2]

assert os.path.exists(f"{repository_path}/v1/00.json"), "sm83 directory is not checked out"

SUPPORTED_OPCODES = ([
    (0x00,"nop"), # NOP
    # (0x02,"ld"), # LD [BC], A
    # (0x12,"ld"), # LD A, [BC]
    # (0x40,"ld"), # LD B, B
    # (0x47,"ld"), # LD B, A
    # (0x49,"ld"), # LD C, C
    # (0x52,"ld"), # LD D, D
    # (0x5B,"ld"), # LD E, E
    # (0x64,"ld"), # LD H, H
    # (0x6D,"ld"), # LD L, L
    # (0x78,"ld"), # LD A, B
    # (0x7F,"ld"), # LD A, A
])

for info in SUPPORTED_OPCODES:
    opcode = info[0]
    insn = info[1]
    input_filename = os.path.join(f"{repository_path}/v1", f"{opcode:02X}.json")
    output_filename = f"{tests_path}/sm83_{opcode:02X}.cpp"
    with open(input_filename, "r") as input_fn, open(output_filename, "w", encoding="utf-8") as output_fn:
        input_json = json.load(input_fn)

        output_fn.write(f"// File autogenerated by {script_path}\n")
        output_fn.write(f"#include <test/include/acutest.h>\n\n")
        output_fn.write(f"#include <cpu/include/instruction_{insn}.hpp>\n")
        output_fn.write(f"#include <cpu/include/registers.hpp>\n")
        output_fn.write(f"#include <memory/include/memory.hpp>\n\n")

        output_fn.write(f"using namespace pgb::memory;\n")
        output_fn.write(f"using namespace pgb::cpu;\n\n")

        output_fn.write(f"static auto registers = RegisterFile();\n")
        output_fn.write(f"static auto mmap      = MemoryMap(registers, MaxRomBankCount, MaxVramBankCount, MaxEramBankCount, MaxWramBankCount);\n\n")

        test_names = []
        test_content = []

        for test in input_json:
            test_name = test['name'].replace(' ', '_')
            test_names.append(test_name)
            test_content.append(f"""
void test_{test_name}()
{{
    mmap.Reset();
    TEST_ASSERT(mmap.Initialize(MaxRomBankCount, MaxVramBankCount, MaxEramBankCount, MaxWramBankCount).IsSuccess());

    // Initial state
    {{
        auto result = mmap.WriteWord(RegisterType::PC, 0x{test['initial']['pc']:04X});
        TEST_ASSERT(result.IsSuccess());
    }}
    {{
        auto result = mmap.WriteWord(RegisterType::SP, 0x{test['initial']['sp']:04X});
        TEST_ASSERT(result.IsSuccess());
    }}
    {{
        auto result = mmap.WriteByte(RegisterType::A, 0x{test['initial']['a']:02X});
        TEST_ASSERT(result.IsSuccess());
    }}
    {{
        auto result = mmap.WriteByte(RegisterType::B, 0x{test['initial']['b']:02X});
        TEST_ASSERT(result.IsSuccess());
    }}
    {{
        auto result = mmap.WriteByte(RegisterType::C, 0x{test['initial']['c']:02X});
        TEST_ASSERT(result.IsSuccess());
    }}
    {{
        auto result = mmap.WriteByte(RegisterType::D, 0x{test['initial']['d']:02X});
        TEST_ASSERT(result.IsSuccess());
    }}
    {{
        auto result = mmap.WriteByte(RegisterType::E, 0x{test['initial']['e']:02X});
        TEST_ASSERT(result.IsSuccess());
    }}
    {{
        TEST_ASSERT(static_cast<const Nibble>(mmap.WriteFlag(0x{test['initial']['f']:02X})) == 0x00);
    }}
    {{
        auto result = mmap.WriteByte(RegisterType::H, 0x{test['initial']['h']:02X});
        TEST_ASSERT(result.IsSuccess());
    }}
    {{
        auto result = mmap.WriteByte(RegisterType::L, 0x{test['initial']['l']:02X});
        TEST_ASSERT(result.IsSuccess());
    }}
}}
            """)

        for name in test_names:
            output_fn.write(f"void test_{name}(void);\n")

        output_fn.write(f"TEST_LIST = {{\n")
        for name in test_names:
            output_fn.write(f"  {{ \"{name}\", test_{name} }},\n")
        output_fn.write(f"  {{NULL, NULL}}\n")
        output_fn.write(f"}};\n")

        for content in test_content:
            output_fn.write(content)
            output_fn.write("\n")
