import os, sys
import json

script_path = sys.argv[0]
file_path = os.path.join(os.path.dirname(script_path), "Opcodes.json")
test_path = sys.argv[1]

with open(file_path, 'r') as input_fn, open(test_path, 'w', encoding='utf-8') as output_fn:
    input_json = json.load(input_fn)

    output_fn.write(f"// File autogenerated by {script_path}\n")
    output_fn.write(f"#include <test/include/acutest.h>\n\n")
    output_fn.write(f"#include <cstdio>\n\n")
    output_fn.write(f"""#include <cpu/include/instruction.hpp>
#include <cpu/include/instruction_alu.hpp>
#include <cpu/include/instruction_ld.hpp>
#include <cpu/include/instruction_nop.hpp>
#include <cpu/include/instruction_prefix.hpp>
#include <cpu/include/instruction_rsb.hpp>
""")
    output_fn.write(f"\nvoid print_missing_instructions(void);\n")
    output_fn.write(f"""
TEST_LIST = {{
    {{"Print missing instructions", print_missing_instructions}},
    {{NULL, NULL}}
}};

using namespace pgb::cpu::instruction;

#pragma GCC diagnostic ignored "-Waddress"

void print_missing_instructions()
{{
    unsigned char countUnprefixed = 0xFF;
    unsigned char countPrefixCB = 0xFF;
    for (unsigned char i = 0; i < 0xFF; ++i)
    {{
        if (InstructionRegistryNoPrefix::Callbacks[i] == nullptr)
        {{
            --countUnprefixed;
            printf("Missing Instruction %02X\\n", i);
        }}
    }}

    for (unsigned char i = 0; i < 0xFF; ++i)
    {{
        if (InstructionRegistryPrefixCB::Callbacks[i] == nullptr)
        {{
            --countPrefixCB;
            printf("Missing Instruction CB %02X\\n", i);
        }}
    }}
    printf("Unprefixed: %u/256 instructions implemented\\n", countUnprefixed);
    printf("Prefix CB: %u/256 instructions implemented\\n", countPrefixCB);
}}

""")
    unprefixed = input_json["unprefixed"]
    cbprefixed = input_json["cbprefixed"]

    for opcode in unprefixed:
        length = unprefixed[opcode]["bytes"]
        output_fn.write(f"static_assert(InstructionRegistryNoPrefix::Callbacks[0x{int(opcode, 16):02X}] == nullptr || InstructionRegistryNoPrefix::Lengths[0x{int(opcode, 16):02X}] == {length});\n")

    for opcode in cbprefixed:
        length = cbprefixed[opcode]["bytes"]
        output_fn.write(f"static_assert(InstructionRegistryPrefixCB::Callbacks[0x{int(opcode, 16):02X}] == nullptr || InstructionRegistryPrefixCB::Lengths[0x{int(opcode, 16):02X}] == {length});\n")

